### ISSUE TITLE
random_sens and random_fps hardcore settings duplicate

### ISSUE THREAD

**Issue by CC3301** [CC3301/csgo-strat-generator#9]
The random_* hardcore settings are technically not duplicate anymore since (https://github.com/CC3301/csgo-strat-generator/commit/290b577192c6f64dd205120b514b57242483e229). However it can happen that the raw, unprocessed keyword is shown as additional hardcore setting in the output when difficulty is above 10.

**Comment by CC3301** [comment]
The random_* settings are currently disabled. Preventing the bug but also removing some features. However, development will focus on other, more important things.

**Comment by dbteetime** [comment]
here neugga
